{{- if .Values.mcp.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "sbomscanner.fullname" . }}-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbomscanner.labels" .| nindent 4 }}
    app.kubernetes.io/component: mcp
{{- end }}
