{{- if eq .Values.auditScanner.serviceAccountName "audit-scanner" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.auditScanner.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admission-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "admission-controller.annotations" . | nindent 4 }}
{{- end }}
