{{- if .Values.telemetry.metrics }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "admission-controller.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admission-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "admission-controller.annotations" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: {{ .Values.ports.metrics }}
  selector:
    {{- include "admission-controller.selectorLabels" . | nindent 4 }}
{{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "admission-controller.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admission-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "admission-controller.annotations" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.ports.webhook }}
  selector:
{{- include "admission-controller.selectorLabels" . | nindent 4 }}
