---
clusterScoped: true # for ClusterAdmissionPolicy, or AdmissionPolicy
metadata:
  name: allow-privilege-escalation-psp
  namespace: default # used when not clusterScoped, and kind is AdmissionPolicy
spec:
  module:
    repository: "ghcr.io/kubewarden/policies/allow-privilege-escalation-psp"
    tag: "v0.1.11"
  mode: "protect"
  mutating: false
  settings:
    default_allow_privilege_escalation: true
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
