---
global:
  cattle:
    systemDefaultRegistry: ghcr.io
module:
  repository: "kubewarden/policies/allow-privilege-escalation-psp"
  tag: "v0.2.7"
clusterScoped: true # for ClusterAdmissionPolicy, or AdmissionPolicy
spec:
  mode: "protect"
  mutating: false
  settings:
    default_allow_privilege_escalation: true
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
