{{- if eq .Values.controller.provider.name "istio" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "network-enforcer.fullname" . }}-istio-fluent-bit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: istio-fluent-bit
    {{- include "network-enforcer.labels" . | nindent 4 }}
{{- end }}
