---
global:
  cattle:
    systemDefaultRegistry: ghcr.io
module:
  repository: "kubewarden/policies/pod-privileged"
  tag: "v0.3.3"
kind: ClusterAdmissionPolicy
spec:
  mode: "protect"
  settings:
  rules:
    -
      apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
