releaseVersion: "UPDATECLI_CHART_VERSION"
semverinc: "UPDATECLI_SEMVERINC_UPDATE"
prerelease_suffix: "UPDATECLI_PRERELEASE_SUFFIX"
github:
  owner: "UPDATECLI_GITHUB_OWNER"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  author: "Kubewarden bot"
  email: "cncf-kubewarden-maintainers@lists.cncf.io"
  user: "UPDATECLI_GITHUB_OWNER"
# The following values are used to update the Hauler manifest.
# The ociArtifacts list all the container images and policies that needs
# to be updated in the manifest
ociArtifacts:
  # Kubewarden container images
  #
  # The workflowUrl field defined in the Kubewarden
  # container images is the url used to validate the identity with cosign
  #
  # The skipVersionFromRegistry field defined in the Kubewarden images is a
  # flag to skip update of the images version in the Helm chart with the
  # version in the registry. These container image should use the container
  # image defined in the release process
  - file: "charts/kubewarden-controller/values.yaml"
    key: "$.image.tag"
    image: "ghcr.io/kubewarden/kubewarden-controller"
    workflowUrl: "https://github.com/kubewarden/kubewarden-controller/.github/workflows/release.yml@refs/tags"
    skipVersionFromRegistry: true
  - file: "charts/kubewarden-controller/values.yaml"
    key: "$.auditScanner.image.tag"
    image: "ghcr.io/kubewarden/audit-scanner"
    workflowUrl: "https://github.com/kubewarden/audit-scanner/.github/workflows/release.yml@refs/tags"
    skipVersionFromRegistry: true
  - file: "charts/kubewarden-defaults/values.yaml"
    key: "$.policyServer.image.tag"
    image: "ghcr.io/kubewarden/policy-server"
    workflowUrl: "https://github.com/kubewarden/policy-server/.github/workflows/release.yml@refs/tags"
    skipVersionFromRegistry: true
  # Policies
  - image: ghcr.io/kubewarden/policies/allow-privilege-escalation-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.allowPrivilegeEscalationPolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/host-namespaces-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.hostNamespacePolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/pod-privileged
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.podPrivilegedPolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/user-group-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.userGroupPolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/hostpaths-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.hostPathsPolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/capabilities-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.capabilitiesPolicy.module.tag"
  # Third party dependencies
  - image: ghcr.io/kyverno/policy-reporter
    file: "charts/kubewarden-controller/values.yaml"
    key: "$.policy-reporter.image.tag"
    strict: true
  - image: ghcr.io/kyverno/policy-reporter-ui
    file: "charts/kubewarden-controller/values.yaml"
    key: "$.policy-reporter.ui.image.tag"
    strict: true
  - image: ghcr.io/rancher/kuberlr-kubectl
    file: "charts/kubewarden-controller/values.yaml"
    key: "$.preDeleteJob.image.tag"
# The helmCharts list all the Helm charts listed in the Hauler that needs to be
# updated regurlarly. This list should be in the same order as defined in the
# charts/hauler_manifest.yaml file.
helmCharts:
  - name: kubewarden-crds
    file: "charts/kubewarden-crds/Chart.yaml"
    versionKey: "$.version"
  - name: kubewarden-controller
    file: "charts/kubewarden-controller/Chart.yaml"
    versionKey: "$.version"
  - name: kubewarden-defaults
    file: "charts/kubewarden-defaults/Chart.yaml"
    versionKey: "$.version"
  - name: policy-reporter
    file: "charts/kubewarden-controller/Chart.yaml"
    versionKey: "$.dependencies[0].version"
    repository: https://kyverno.github.io/policy-reporter
  - name: openreports
    file: "charts/kubewarden-crds/Chart.yaml"
    versionKey: "$.dependencies[0].version"
    repository: https://openreports.github.io/reports-api
