releaseVersion: "UPDATECLI_CHART_VERSION"
semverinc: "UPDATECLI_SEMVERINC_UPDATE"
prerelease_suffix: "UPDATECLI_PRERELEASE_SUFFIX"
github:
  owner: "UPDATECLI_GITHUB_OWNER"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  author: "Kubewarden bot"
  email: "cncf-kubewarden-maintainers@lists.cncf.io"
  user: "UPDATECLI_GITHUB_OWNER"
