{{ if or .Values.telemetry.metrics.enabled .Values.telemetry.tracing.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: kubewarden
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "kubewarden-controller.annotations" . | nindent 4 }}
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
      batch:
    exporters:
      {{- if and .Values.telemetry.tracing.enabled .Values.telemetry.tracing.jaeger.endpoint }}
      otlp/jaeger:
        endpoint: {{ .Values.telemetry.tracing.jaeger.endpoint }}
        {{- if hasKey .Values.telemetry.tracing.jaeger "tls" }}
        {{- if .Values.telemetry.tracing.jaeger.tls.insecure }}
        tls:
          insecure: {{ .Values.telemetry.tracing.jaeger.tls.insecure }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- if and .Values.telemetry.metrics.enabled .Values.telemetry.metrics.port }}
      prometheus:
        endpoint: ":{{ .Values.telemetry.metrics.port }}"
      {{- end }}
    service:
      pipelines:
        {{- if and .Values.telemetry.metrics.enabled .Values.telemetry.metrics.port }}
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [prometheus]
        {{- end }}
        {{- if and .Values.telemetry.tracing.enabled .Values.telemetry.tracing.jaeger.endpoint }}
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
        {{- end }}
{{ end }}
