apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: default
  finalizers:
    - kubewarden
  annotations:
    "helm.sh/hook": "post-install"
spec:
  image: {{ .Values.policyServer.image.repository }}:{{ .Values.policyServer.image.tag }}
  serviceAccountName: {{ .Values.policyServer.serviceAccountName }}
  replicas: {{ .Values.policyServer.replicaCount | default 1 }}
  annotations:
    {{ if .Values.telemetry.enabled }}
      "sidecar.opentelemetry.io/inject": "true"
    {{ end }}
    {{- range $key, $value := .Values.policyServer.annotations }}
      {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{ if or .Values.policyServer.env .Values.telemetry.enabled }}
  env:
    {{- if .Values.telemetry.enabled }}
    - name: KUBEWARDEN_ENABLE_METRICS
      value: "1"
    - name: KUBEWARDEN_LOG_FMT
      value: otlp
    {{- end }}
    {{- range .Values.policyServer.env }}
    - name: {{ .name | quote }}
      value: {{ .value | quote }}
    {{- end }}
  {{- end }}
