# Secret used to store the controller webhook certificate and key. This secret
# is empty because it will be populated by the controller later. This is necessary
# to avoid errors when deploying the controller deployment due a missing secret
# used in the volumes
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.tls.controllerCertificateSecretName }}"
