---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubewarden-controller.fullname" . }}-metrics-service
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
spec:
  ports:
  {{- if .Values.telemetry.enabled }}
  - name: metrics
    port: 8080
    targetPort: 8080
  {{- end}}
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "kubewarden-controller.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubewarden-controller.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
{{- include "kubewarden-controller.selectorLabels" . | nindent 4 }}
