apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubewarden-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "kubewarden-controller.annotations" . | nindent 4 }}

{{- if eq .Values.experimental.auditScanner.serviceAccountName "audit-scanner" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.experimental.auditScanner.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "kubewarden-controller.annotations" . | nindent 4 }}
{{ end }}
