apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sbomscanner.fullname" . }}-worker-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbomscanner.labels" .| nindent 4 }}
    app.kubernetes.io/component: worker-node
spec:
  selector:
    matchLabels:
      {{ include "sbomscanner.selectorLabels" .| nindent 6 }}
      app.kubernetes.io/component: worker-node
  template:
    metadata:
      labels:
        {{ include "sbomscanner.labels" .| nindent 8 }}
        app.kubernetes.io/component: worker-node
    spec:
      serviceAccountName: {{ include "sbomscanner.fullname" . }}-worker-node
      initContainers:
        - name: init
          image: '{{ template "system_default_registry" . }}{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}'
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            {{ include "sbomscanner.securityContext" . | nindent 12 }}
          args:
            - --init
            - -nats-url
            - {{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222
          {{- if .Values.worker.logLevel }}
            - -log-level={{ .Values.worker.logLevel }}
          {{- end }}
          volumeMounts:
            - mountPath: "/nats/tls"
              name: nats-tls
              readOnly: true
      containers:
        - name: worker
          image: '{{ template "system_default_registry" . }}{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}'
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            runAsUser: 0
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
              add:
                - "DAC_READ_SEARCH"
          args:
            - -nats-url
            - {{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222
            {{- if .Values.worker.trivyDBRepository }}
            - -trivy-db-repository={{ .Values.worker.trivyDBRepository | quote }}
            {{- end }}
            {{- if .Values.worker.trivyJavaDBRepository }}
            - -trivy-java-db-repository={{ .Values.worker.trivyJavaDBRepository | quote }}
            {{- end }}
            - -installation-namespace={{ .Release.Namespace }}
            {{- if .Values.worker.logLevel }}
            - -log-level={{ .Values.worker.logLevel }}
            {{- end }}
            - -mode=node
            - -node-name=$(NODE_NAME)
          {{- if and .Values.worker .Values.worker.resources }}
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /livez
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: true
              mountPropagation: None
            - mountPath: /var/run/worker
              name: run-volume
            - mountPath: /tmp
              name: tmp-dir
            - mountPath: "/nats/tls"
              name: nats-tls
              readOnly: true
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: run-volume
          emptyDir: {}
        - name: tmp-dir
          emptyDir: {}
        - name: nats-tls
          secret:
            secretName: {{ include "sbomscanner.fullname" . }}-nats-worker-client-tls
