{{- if .Values.controller.nodeScan.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sbomscanner.fullname" . }}-worker-node
  labels:
    {{ include "sbomscanner.labels" .| nindent 4 }}
    app.kubernetes.io/component: worker-node
rules:
  - apiGroups:
      - sbomscanner.kubewarden.io
    resources:
      - vexhubs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - sbomscanner.kubewarden.io
    resources:
      - nodescanjobs
      - nodescanjobs/status
      - nodescanconfigurations
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - storage.sbomscanner.kubewarden.io
    resources:
      - nodesboms
      - nodevulnerabilityreports
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
{{- end }}
