apiVersion: v1
kind: Service
metadata:
  name: {{ include "sbomscanner.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbomscanner.labels" .| nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    {{ include "sbomscanner.selectorLabels" .| nindent 4 }}
    app.kubernetes.io/component: storage
