---
clusterScoped: true # for ClusterAdmissionPolicy, or AdmissionPolicy
metadata:
  namespace: default # used when kind is AdmissionPolicy
spec:
  module:
    repository: "ghcr.io/kubewarden/policies/user-group-psp"
    tag: "v0.2.0"
  mode: "protect"
  mutating: false
  rules:
    -
      apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
  settings:
    run_as_user:
      rule: ""
    run_as_group:
      rule: ""
    supplemental_groups:
      rule: ""
