---
apiVersion: policies.kubewarden.io/v1
{{- if eq .Values.clusterScoped true }}
kind: ClusterAdmissionPolicy
{{- else }}
kind: AdmissionPolicy
{{- end }}
metadata:
  name: {{ .Release.name }}
  {{- if eq .Values.clusterScoped false }}
  namespace: {{ .Values.metadata.namespace }}
  {{- end }}
spec:
  module: '{{ .Values.spec.module.repository }}:{{ .Values.spec.module.tag }}'
  mode: {{ .Values.spec.mode }}
  mutating: {{ .Values.spec.mutating }}
  settings:
    default_allow_privilege_escalation: {{ .Values.spec.settings.default_allow_privilege_escalation }}
  rules:
    {{- toYaml .Values.spec.rules | nindent 4 }}
