---
global:
  cattle:
    systemDefaultRegistry: ghcr.io
module:
  repository: "kubewarden/policies/apparmor-psp"
  tag: "v0.1.9"
clusterScoped: true # for ClusterAdmissionPolicy, or AdmissionPolicy
spec:
  module:
  mode: "protect"
  rules:
    -
      apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
  settings: |
    allowed_profiles:
      # list of allowed AppArmor profiles.
      # If no profile is defined, Kubernetes will leave the final choice to the
      # underlying container runtime.
      - runtime/default # more secure than the predefined 'unconfined' profile
      # - localhost/my-special-workload
