apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-controller-manager
  labels:
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
