{{ if .Values.bestPracticePolicies.enabled }}
{{- range $namespace := .Values.bestPracticePolicies.namespaces }}
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: AdmissionPolicy
metadata:
  name: {{ $.Values.bestPracticePolicies.podPrivilegedPolicy.name }}
  namespace: {{ $namespace }}
spec:
  policyServer: {{ $.Values.policyServer.name }}
  mode: {{ $.Values.bestPracticePolicies.defaultPolicyMode }}
  module: {{ $.Values.bestPracticePolicies.podPrivilegedPolicy.module }}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
{{- end}}
{{ end }}
