apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.policyServer.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubewarden-context-watcher
rules:
{{- range .Values.policyServer.permissions }}
- apiGroups:
  - {{ .apiGroup | quote }}
  resources: {{ .resources | toJson }}
  verbs:
  - list
  - watch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubewarden-context-watcher
subjects:
- kind: ServiceAccount
  name: {{ .Values.policyServer.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kubewarden-context-watcher
  apiGroup: rbac.authorization.k8s.io
