apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kubewarden-defaults.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy-server
  annotations:
    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
  name: {{ .Values.policyServer.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubewarden-defaults.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy-server
  annotations:
    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
  name: kubewarden-context-watcher
rules:
{{- range .Values.policyServer.permissions }}
- apiGroups:
  - {{ .apiGroup | quote }}
  resources: {{ .resources | toJson }}
  verbs:
  - get
  - list
  - watch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kubewarden-defaults.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy-server
  annotations:
    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
  name: kubewarden-context-watcher
subjects:
- kind: ServiceAccount
  name: {{ .Values.policyServer.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kubewarden-context-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: policy-optimizer-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewarden-defaults.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy-server
  annotations:
    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: policy-optimizer-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewarden-defaults.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy-server
  annotations:
    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: policy-optimizer-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.policyServer.serviceAccountName }}
  namespace: {{ .Release.Namespace }}

