---
apiVersion: policies.kubewarden.io/v1
{{- if eq .Values.clusterScoped true }}
kind: ClusterAdmissionPolicy
{{- else }}
kind: AdmissionPolicy
{{- end }}
metadata:
  name: {{ .Release.name }}
  {{- if eq .Values.clusterScoped false }}
  namespace: {{ .Values.metadata.namespace }}
  {{- end }}
spec:
  module: '{{ .Values.spec.module.repository }}:{{ .Values.spec.module.tag }}'
  mode: {{ .Values.spec.mode }}
  mutating: {{ .Values.spec.mutating }}
  rules:
    {{- toYaml .Values.spec.rules | nindent 4 }}
  settings:
    {{- if eq .Values.spec.mutating true }}
    fallbackRuntime: {{ .Values.spec.settings.fallbackRuntime }}
    {{- end }}
    defaultRuntimeReserved: {{ .Values.spec.settings.defaultRuntimeReserved }}
    reservedRuntimes:
    {{- toYaml .Values.spec.settings.reservedRuntimes | replace "|\n" "" | nindent 2 }}
