apiVersion: v1
kind: Service
metadata:
  name: {{ include "sbomscanner.fullname" . }}-controller-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sbomscanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    {{- include "sbomscanner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
