apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sbomscanner.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbomscanner.labels" .| nindent 4 }}
    app.kubernetes.io/component: controller
