name: Sync SBOMscanner Helm chart

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release-sbomscanner]

jobs:
  sync-sbomscanner:
    name: Sync SBOMscanner Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@5bda7da77bf4d181bce5f807d73d832b62062acf # v3.3.0

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update SBOMscanner helm chart
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: |-
          updatecli compose apply --file ./updatecli/sbomscanner-release.yaml
