name: Sync Adm Controller Helm charts

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release-adm-controller]

jobs:
  sync-kubewarden-controller:
    name: Sync Adm Controller Helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@d422ba543720d01a96d4c3e3ab8544cc188cd711 # v3.5.0

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update Adm Controller helm charts
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: |-
          updatecli compose apply --file ./updatecli/adm-controller-release.yaml
